import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Heart, Share2, MessageCircle, CheckCircle, Radio } from 'lucide-react';
import { useState } from 'react';
import { PULSE_LOGO_URI } from '../utils/logoPlaceholder';
export function CreatorProfile(props) {
    const [isFollowing, setIsFollowing] = useState(false);
    const [expandBio, setExpandBio] = useState(false);
    return (_jsxs("div", { className: "bg-gradient-to-b from-purple-950/40 to-slate-950/40 rounded-xl border border-purple-700/30 overflow-hidden hover:border-purple-500/50 transition-all", children: [_jsx("div", { className: "h-20 bg-gradient-to-r from-purple-600/20 to-purple-500/10" }), _jsxs("div", { className: "px-6 pb-6 -mt-8 relative", children: [_jsxs("div", { className: "flex flex-col sm:flex-row items-start sm:items-end gap-3 sm:gap-4 mb-4", children: [_jsxs("div", { className: "relative", children: [_jsx("img", { src: props.avatar, alt: props.name, className: "w-20 h-20 rounded-lg border-4 border-slate-900 object-cover", onError: (e) => {
                                            e.currentTarget.src = PULSE_LOGO_URI;
                                        } }), props.isLive && (_jsx("div", { className: "absolute top-1 right-1 w-3 h-3 bg-red-500 rounded-full border border-white animate-pulse" }))] }), _jsxs("div", { className: "flex-1 w-full sm:w-auto", children: [_jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsx("h3", { className: "text-lg sm:text-xl font-bold text-purple-300", children: props.name }), props.verified && _jsx(CheckCircle, { size: 18, className: "text-cyan-400" })] }), _jsx("p", { className: "text-sm text-slate-400 font-mono", children: props.category })] })] }), _jsxs("div", { className: "grid grid-cols-3 gap-3 mb-4 p-3 bg-slate-800/30 rounded-lg border border-purple-700/20", children: [_jsxs("div", { className: "text-center", children: [_jsx("p", { className: "text-xs font-mono text-slate-400", children: "Followers" }), _jsx("p", { className: "text-lg font-bold text-purple-300", children: props.followers })] }), _jsxs("div", { className: "text-center border-l border-r border-purple-700/20", children: [_jsx("p", { className: "text-xs font-mono text-slate-400", children: "Clips" }), _jsx("p", { className: "text-lg font-bold text-purple-300", children: props.clips })] }), _jsxs("div", { className: "text-center", children: [_jsx("p", { className: "text-xs font-mono text-slate-400", children: "Status" }), _jsx("p", { className: "text-lg font-bold text-red-400 flex items-center justify-center gap-1", children: props.isLive ? (_jsxs(_Fragment, { children: [_jsx(Radio, { size: 12, className: "animate-pulse" }), "LIVE"] })) : ('Offline') })] })] }), _jsx("p", { className: `text-sm text-slate-300 mb-4 ${!expandBio && 'line-clamp-2'}`, children: props.bio }), props.bio.length > 50 && (_jsx("button", { onClick: () => setExpandBio(!expandBio), className: "text-xs text-purple-400 hover:text-purple-300 mb-4 font-mono", children: expandBio ? 'Show less' : 'Show more' })), _jsxs("div", { className: "flex gap-2 mb-6", children: [_jsx("button", { onClick: () => setIsFollowing(!isFollowing), className: `flex-1 px-4 py-3 rounded-lg font-mono font-bold text-xs uppercase tracking-wider transition-all active:scale-95 ${isFollowing
                                    ? 'bg-purple-600 text-white'
                                    : 'bg-gradient-to-r from-purple-600 to-purple-500 text-white hover:from-purple-500 hover:to-purple-400'}`, children: isFollowing ? '✓ Following' : 'Follow' }), _jsx("button", { className: "flex-1 px-4 py-3 border border-purple-700/50 text-purple-300 font-mono font-bold text-xs uppercase tracking-wider rounded-lg hover:bg-purple-500/10 transition-all active:scale-95", children: "Message" })] }), _jsxs("div", { className: "flex gap-3 p-3 bg-slate-800/30 rounded-lg border border-purple-700/20", children: [_jsxs("button", { className: "flex items-center gap-1 text-xs text-slate-400 hover:text-red-400 transition-colors", children: [_jsx(Heart, { size: 14 }), "Like"] }), _jsxs("button", { className: "flex items-center gap-1 text-xs text-slate-400 hover:text-purple-300 transition-colors", children: [_jsx(MessageCircle, { size: 14 }), "Comment"] }), _jsxs("button", { className: "flex items-center gap-1 text-xs text-slate-400 hover:text-cyan-300 transition-colors", children: [_jsx(Share2, { size: 14 }), "Share"] })] })] }), _jsxs("div", { className: "border-t border-purple-700/30 p-6 bg-slate-950/30", children: [_jsx("h4", { className: "text-sm font-bold text-purple-300 mb-3 font-mono", children: "Recent Clips" }), _jsx("div", { className: "grid grid-cols-1 gap-2", children: props.recentClips.slice(0, 3).map((clip) => (_jsxs("div", { className: "flex gap-2 p-2 bg-slate-800/50 rounded-lg hover:bg-slate-800/80 transition-all cursor-pointer", children: [_jsx("img", { src: clip.thumbnail, alt: clip.title, className: "w-12 h-12 rounded object-cover flex-shrink-0", onError: (e) => {
                                        e.currentTarget.src = PULSE_LOGO_URI;
                                    } }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-xs font-mono text-slate-300 truncate", children: clip.title }), _jsxs("p", { className: "text-xs text-slate-500", children: [clip.views, " \u2022 ", clip.likes, " likes"] })] })] }, clip.id))) })] })] }));
}
