import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Play, Users, Zap, Heart } from 'lucide-react';
import { useState } from 'react';
import { LiveViewerModal } from './LiveViewerModal';
import { PULSE_LOGO_URI } from '../utils/logoPlaceholder';
export function LiveStreamCard(props) {
    const [showViewer, setShowViewer] = useState(false);
    const [liked, setLiked] = useState(false);
    return (_jsxs(_Fragment, { children: [_jsxs("div", { className: "group relative bg-slate-900/50 rounded-lg border border-purple-700/20 overflow-hidden hover:border-purple-500/40 transition-all duration-300 hover:shadow-[0_0_30px_rgba(153,69,255,0.2)]", children: [_jsxs("div", { className: "relative overflow-hidden aspect-video bg-slate-950 flex items-center justify-center", children: [_jsx("img", { src: props.thumbnail, alt: props.title, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-300", loading: "lazy", onError: (e) => {
                                    e.currentTarget.src = PULSE_LOGO_URI;
                                } }), _jsxs("div", { className: "absolute top-2 left-2 flex items-center gap-2 px-3 py-1 bg-red-600/90 backdrop-blur-sm rounded-full", children: [_jsx("div", { className: "w-2 h-2 bg-red-300 rounded-full animate-pulse" }), _jsx("span", { className: "text-xs font-mono font-bold text-white uppercase", children: "LIVE" })] }), _jsxs("div", { className: "absolute top-2 right-2 flex items-center gap-1 px-3 py-1 bg-black/70 backdrop-blur-sm rounded-full text-xs font-mono text-slate-200", children: [_jsx(Users, { size: 12 }), props.viewers] }), _jsx("div", { className: "absolute inset-0 bg-black/0 group-hover:bg-black/30 transition-all duration-300 flex items-center justify-center", children: _jsx("button", { onClick: () => setShowViewer(true), className: "w-12 h-12 rounded-full bg-purple-600/80 backdrop-blur-sm flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all duration-300 hover:bg-purple-500", children: _jsx(Play, { size: 24, className: "text-white fill-white ml-1" }) }) }), _jsx("div", { className: "absolute bottom-2 right-2 bg-black/80 px-2 py-1 rounded text-xs font-mono text-slate-200", children: props.liveTime })] }), _jsxs("div", { className: "p-4 space-y-3", children: [_jsx("h3", { className: "text-sm font-bold text-slate-200 line-clamp-2 group-hover:text-purple-300 transition-colors", children: props.title }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("img", { src: props.avatar, alt: props.streamer, className: "w-8 h-8 rounded-full object-cover", onError: (e) => {
                                            e.currentTarget.src = PULSE_LOGO_URI;
                                        } }), _jsx("div", { className: "flex-1 min-w-0", children: _jsx("p", { className: "text-xs font-mono text-slate-300 truncate", children: props.streamer }) }), _jsx("span", { className: "text-xs px-2 py-1 bg-purple-600/20 text-purple-300 rounded font-mono", children: props.category })] }), _jsxs("div", { className: "flex gap-2 pt-2", children: [_jsx("button", { onClick: () => setLiked(!liked), className: `flex-1 px-2 py-3 rounded-lg font-mono font-bold text-xs uppercase tracking-wider transition-all active:scale-95 ${liked
                                            ? 'bg-red-600/30 text-red-300 border border-red-500/50'
                                            : 'bg-slate-800/50 text-slate-300 border border-slate-700/50 hover:border-red-500/50'}`, children: _jsx(Heart, { size: 14, className: `${liked ? 'fill-red-300' : ''}` }) }), _jsxs("button", { onClick: () => setShowViewer(true), className: "flex-1 px-2 py-3 rounded-lg bg-gradient-to-r from-purple-600 to-purple-500 text-white font-mono font-bold text-xs uppercase tracking-wider hover:from-purple-500 hover:to-purple-400 transition-all active:scale-95 flex items-center justify-center gap-1", children: [_jsx(Zap, { size: 14 }), "Watch & Clip"] })] })] })] }), showViewer && (_jsx(LiveViewerModal, { title: props.title, streamer: props.streamer, avatar: props.avatar, viewers: props.viewers, onClose: () => setShowViewer(false) }))] }));
}
