[features]
seeds = false
skip-lint = false

[programs.devnet]
abraxas = "GBcDay9fAqn6WPCBVRkkar3VXgKS2MRozH3tWcG2SZXm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
