import type {
  AgentActionLog,
  AthleteToken,
  FutureAssetClass,
  LaCasaDepositRecord,
  VaultSummary,
} from './types';

export const starterVaults: VaultSummary[] = [
  {
    id: 'vault-oym-prime',
    name: 'OYM Prime Vault',
    assetType: 'athlete_equity',
    depositedAmount: 142500,
    vaultValue: 159820,
    policy: 'growth',
    circuitState: 'normal',
    assignedAgent: 'Sophia Sentinel',
    laCasaDeposits: 24,
    athleteExposure: 118000,
    protectiveBuffer: 11.4,
  },
  {
    id: 'vault-worldlabs-rwa',
    name: 'World Labs Expansion Vault',
    assetType: 'real_estate',
    depositedAmount: 38500,
    vaultValue: 40120,
    policy: 'balanced',
    circuitState: 'warning',
    assignedAgent: 'Sophia Yield',
    laCasaDeposits: 6,
    athleteExposure: 0,
    protectiveBuffer: 15.8,
  },
];

export const starterAthleteTokens: AthleteToken[] = [
  {
    id: 'token-cdubb',
    symbol: '$CDUBB',
    name: 'C Dubb',
    price: 18.42,
    changePct: 8.4,
    exposure: 52000,
    valueGrowthPct: 24.6,
    trainingScore: 91,
    statsIndex: 88,
    nilRewards: 6300,
    streak: 11,
    vaultId: 'vault-oym-prime',
    kingSignal: 'accelerate',
    suggestions: [
      {
        id: 'cdubb-drills',
        title: 'Explosive finishing block',
        focus: 'training',
        rationale: 'Rim pressure is converting at a higher clip than perimeter reps. Keep the edge compounding.',
        expectedImpactBps: 180,
        status: 'queued',
      },
      {
        id: 'cdubb-nil',
        title: 'Weekend NIL drop',
        focus: 'nil',
        rationale: 'Training streak momentum supports a short, premium social activation window.',
        expectedImpactBps: 90,
        status: 'queued',
      },
    ],
  },
  {
    id: 'token-ajwill',
    symbol: '$AJWILL',
    name: 'AJ Will',
    price: 14.76,
    changePct: 5.1,
    exposure: 38000,
    valueGrowthPct: 18.2,
    trainingScore: 86,
    statsIndex: 83,
    nilRewards: 4120,
    streak: 8,
    vaultId: 'vault-oym-prime',
    kingSignal: 'build',
    suggestions: [
      {
        id: 'ajwill-shooting',
        title: 'Corner shooting ladder',
        focus: 'stats',
        rationale: 'Corner efficiency is the cleanest path to a faster valuation multiple lift.',
        expectedImpactBps: 140,
        status: 'queued',
      },
      {
        id: 'ajwill-strength',
        title: 'Lower-body strength phase',
        focus: 'training',
        rationale: 'The current workload supports a short power block without volatility in game output.',
        expectedImpactBps: 110,
        status: 'queued',
      },
    ],
  },
  {
    id: 'token-hailee',
    symbol: '$HAILEE',
    name: 'Hailee',
    price: 11.93,
    changePct: 11.8,
    exposure: 28000,
    valueGrowthPct: 27.4,
    trainingScore: 94,
    statsIndex: 90,
    nilRewards: 5085,
    streak: 13,
    vaultId: 'vault-oym-prime',
    kingSignal: 'protect',
    suggestions: [
      {
        id: 'hailee-recovery',
        title: 'Recovery-biased skill split',
        focus: 'training',
        rationale: 'Momentum is strong enough to prioritize preservation before the next acceleration window.',
        expectedImpactBps: 95,
        status: 'queued',
      },
      {
        id: 'hailee-brand',
        title: 'Brand-safe NIL cadence',
        focus: 'nil',
        rationale: 'Keep sponsor attention high while reducing overtraining risk into the next event cycle.',
        expectedImpactBps: 120,
        status: 'queued',
      },
    ],
  },
];

export const starterLaCasaDeposits: LaCasaDepositRecord[] = [
  {
    id: 'lacasa-1',
    label: 'La Casa Genesis #014',
    collection: 'La Casa Genesis',
    stablecoinAmount: 12500,
    vaultId: 'vault-oym-prime',
    athleteTokenId: 'token-cdubb',
    depositedAt: '2026-03-17T14:30:00.000Z',
  },
  {
    id: 'lacasa-2',
    label: 'La Casa Athlete Series #031',
    collection: 'La Casa Athlete Series',
    stablecoinAmount: 8200,
    vaultId: 'vault-oym-prime',
    athleteTokenId: 'token-hailee',
    depositedAt: '2026-03-18T09:05:00.000Z',
  },
];

export const starterFutureAssetClasses: FutureAssetClass[] = [
  {
    id: 'future-real-estate',
    title: 'Real Estate Development',
    description: 'Renovation upgrades, rent yield, and occupancy quality become the development loop that grows property-backed vault value.',
    status: 'coming_soon',
  },
  {
    id: 'future-trading',
    title: 'Trading Portfolios',
    description: 'King AI can later optimize portfolio discipline, execution quality, and risk-adjusted returns using the same growth mechanics.',
    status: 'blueprint',
  },
];

export const starterLogs: AgentActionLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-03-18T12:00:00.000Z',
    vaultId: 'vault-oym-prime',
    action: 'King AI refreshed athlete equity guidance',
    detail: 'Training cadence and NIL sequencing were repriced across the OYM basket.',
  },
  {
    id: 'log-2',
    timestamp: '2026-03-18T13:15:00.000Z',
    vaultId: 'vault-worldlabs-rwa',
    action: 'Circuit protective payout staged',
    detail: 'Expansion Vault widened its buffer after volatility crossed warning thresholds.',
  },
];
